### ISSUE TITLE
Gör citatet på två rader

### ISSUE THREAD

**Issue by dreifeldt** [speedment/speedment-com#38]
Dela upp citatet i 2 rader med indrag före ordet action:

Speedment enables you to perform database 
           actions using Java 8 Streams syntax instead of SQL

Hur gör man på mobiler? Kan fonten skalas ner i storlek. Vad är enklaste lösningen?

**Comment by rossii123** [comment]
Jag la till en <br/> så att det blir en ny rad efter action
