### ISSUE TITLE
3 vita bilderna mot den gröna bakgrunden

### ISSUE THREAD

**Issue by dreifeldt** [speedment/speedment-com#39]
Biderna ska vara mindre i storlek. Kolla in spring.us för att få skalan.
Elis lägger 3 nya vektorbilder i dropbox på Marketing/Design/Hemsidan

**Comment by Pyknic** [comment]
I can't find any site called [spring.us](http://spring.us). Do you have a link? @dreifeldt

**Comment by dreifeldt** [comment]
spring.io
